/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "docusaurus-theme-zen",
  "titleDelimiter": "-",
  "url": "https://wrm244.github.io",
  "baseUrl": "/docusaurus-theme-zen/",
  "favicon": "/assets/images/social/avatar.ico",
  "organizationName": "",
  "projectName": "docusaurus-theme-zen",
  "tagline": "docusaurus的一款美观便捷主题",
  "onBrokenLinks": "ignore",
  "themeConfig": {
    "image": "/assets/images/social/avatar.png",
    "announcementBar": {
      "id": "announcementBar-3",
      "content": "🎉欢迎浏览<a href=\"https://github.com/wrm244/docusaurus-theme-zen/\" target=\"_blank\">docusaurus-theme-zen</a>",
      "isCloseable": true
    },
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "forest"
      }
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#000000",
          "backgroundColor": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(0, 128, 0)"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "rgb(0, 112, 193)"
            }
          },
          {
            "types": [
              "number",
              "variable",
              "inserted"
            ],
            "style": {
              "color": "rgb(9, 134, 88)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(0, 0, 0)"
            }
          },
          {
            "types": [
              "constant",
              "char"
            ],
            "style": {
              "color": "rgb(129, 31, 63)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(128, 0, 0)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 0, 0)"
            }
          },
          {
            "types": [
              "deleted",
              "string"
            ],
            "style": {
              "color": "rgb(163, 21, 21)"
            }
          },
          {
            "types": [
              "changed",
              "punctuation"
            ],
            "style": {
              "color": "rgb(4, 81, 165)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "rgb(0, 0, 255)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(38, 127, 153)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "php",
        "rust",
        "toml"
      ],
      "defaultLanguage": "javascript",
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ]
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "docusaurus-theme-zen"
      },
      {
        "name": "keywords",
        "content": "blog,javascript, nginx,, react, vue, web"
      },
      {
        "name": "keywords",
        "content": " 编程爱好者"
      }
    ],
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "docusaurus-theme-zen",
      "logo": {
        "alt": "your name",
        "src": "/assets/images/social/avatar.png",
        "srcDark": "/assets/images/social/avatar.png"
      },
      "hideOnScroll": false,
      "items": [
        {
          "label": "博客",
          "position": "left",
          "items": [
            {
              "label": "标签",
              "to": "tags"
            },
            {
              "label": "归档",
              "to": "archive"
            },
            {
              "label": "随笔",
              "to": "tags/lifestyle"
            }
          ]
        },
        {
          "label": "笔记",
          "position": "left",
          "to": "docs/stack/",
          "items": [
            {
              "label": "本站的搭建",
              "to": "first-blog"
            },
            {
              "label": "学习栈",
              "to": "docs/stack/"
            }
          ]
        },
        {
          "label": "导航",
          "position": "left",
          "to": "resource"
        },
        {
          "label": "项目",
          "position": "left",
          "to": "project"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "博客",
          "items": [
            {
              "label": "标签",
              "to": "tags"
            },
            {
              "label": "归档",
              "to": "archive"
            }
          ]
        },
        {
          "title": "学习",
          "items": [
            {
              "label": "笔记",
              "to": "docs/stack"
            },
            {
              "label": "项目",
              "to": "project"
            }
          ]
        },
        {
          "title": "社交媒体",
          "items": [
            {
              "label": "关于我",
              "to": "/about"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/wrm244/docusaurus-theme-zen"
            }
          ]
        },
        {
          "title": "更多",
          "items": [
            {
              "label": "友链",
              "to": "friends"
            },
            {
              "label": "导航",
              "to": "resource"
            },
            {
              "html": "<a href=\"https://docusaurus.io/zh-CN/\" target=\"_blank\"><img alt=\"Built with Docusaurus\" style=\"height:50px;margin-top:0.5rem\" src=\"/assets/images/buildwith.png\" /></a> <a href=\"https://www.netlify.com/\" target=\"_blank\"><img alt=\"Built with Netlify\" style=\"height:50px;margin-top:0.5rem\" src=\"/assets/images/netlify-color-accent.svg\" /></a>"
            }
          ]
        }
      ],
      "copyright": "版权所有 © 2023 docusaurus-theme-zen, 此网站使用 <a href=\"https://docusaurus.io/zh-CN/\" target=\"_blank\">Docusaurus</a> 搭建\n      <span id=\"runtime_span\"></span>\n      <script type=\"text/javascript\">function show_runtime(){window.setTimeout(\"show_runtime()\",1000);X=new \n      Date(\"10/16/2022 8:22:00\");\n      Y=new Date();T=(Y.getTime()-X.getTime());M=24*60*60*1000;\n      a=T/M;A=Math.floor(a);b=(a-A)*24;B=Math.floor(b);c=(b-B)*60;C=Math.floor((b-B)*60);D=Math.floor((c-C)*60);\n      runtime_span.innerHTML=\"<br>本站已运行: \"+A+\"天\"+B+\"小时\"+C+\"分\"+D+\"秒\"}show_runtime();</script>"
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "zoom": {
      "selector": ".markdown :not(em) > img",
      "background": {
        "light": "#eef9fd",
        "dark": "rgb(50, 50, 50)"
      },
      "config": {
        "magin": 10,
        "scrollOffset": 0
      }
    },
    "giscus": {
      "repo": "wrm244/docusaurus-theme-zen",
      "repoId": "R_kgDOJZ-VIA",
      "category": "General",
      "categoryId": "DIC_kwDOJZ-VIM4CV95r",
      "loading": "lazy",
      "lang": "zh-CN"
    },
    "liveCodeBlock": {
      "playgroundPosition": "top"
    },
    "socials": {
      "github": "https://github.com/",
      "twitter": "https://twitter.com/",
      "csdn": "https://blog.csdn.net/",
      "juejin": "https://juejin.cn/",
      "qq": "tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=xxxxxxxx&website=www.oicqzone.com",
      "zhihu": "https://www.zhihu.com/"
    }
  },
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "description",
        "content": "docusaurus-theme-zen"
      }
    }
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "docs",
          "sidebarPath": "sidebars.js",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": false,
        "theme": {
          "customCss": [
            "D:\\wiki\\docusaurus-theme-zen\\src\\css\\custom.scss"
          ]
        },
        "sitemap": {
          "changefreq": "daily",
          "priority": 0.5
        }
      }
    ]
  ],
  "themes": [
    [
      "D:\\wiki\\docusaurus-theme-zen\\node_modules\\@easyops-cn\\docusaurus-search-local\\dist\\server\\server\\index.js",
      {
        "hashed": true,
        "language": [
          "en",
          "zh"
        ],
        "indexBlog": true,
        "indexPages": true,
        "indexDocs": true
      }
    ]
  ],
  "markdown": {
    "mermaid": true
  },
  "plugins": [
    "docusaurus-plugin-image-zoom",
    "docusaurus-plugin-sass",
    "D:\\wiki\\docusaurus-theme-zen\\src\\plugin\\plugin-baidu-tongji",
    "D:\\wiki\\docusaurus-theme-zen\\src\\plugin\\plugin-baidu-push",
    [
      "D:\\wiki\\docusaurus-theme-zen\\src\\plugin\\plugin-content-blog",
      {
        "path": "blog",
        "routeBasePath": "/",
        "editLocalizedFiles": false,
        "blogDescription": "docusaurus-theme-zen",
        "blogSidebarCount": 10,
        "blogSidebarTitle": "最近更新",
        "postsPerPage": 10,
        "showReadingTime": true,
        "feedOptions": {
          "type": "all",
          "title": "docusaurus-theme-zen",
          "copyright": "Copyright © 2023 your name Built with Docusaurus. class=\"footer_lin\">"
        }
      }
    ],
    [
      "@docusaurus/plugin-ideal-image",
      {
        "quality": 80,
        "disableInDev": false
      }
    ],
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": true,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "assets/images/social/avatar.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "rgb(51 139 255)"
          }
        ]
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://jsd.onmicrosoft.cn/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "i18n": {
    "defaultLocale": "zh-CN",
    "locales": [
      "en",
      "zh-CN"
    ],
    "localeConfigs": {
      "en": {
        "htmlLang": "en-GB",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "baseUrlIssueBanner": true,
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "clientModules": [],
  "noIndex": false
};
